# .github/workflows/ci-cd.yml

name: CI/CD - Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  # --- DOUBLE CHECK THESE VALUES ---
  PROJECT_ID: aiops-mini-project  # Make sure this is your exact GCP Project ID
  GCP_REGION: us-central1
  REGISTRY_NAME: my-app-registry
  SERVICE_NAME: diabetes-api-service 
  # --- --- --- --- --- --- --- ---

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth # <-- Give the step an ID
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      # --- THIS IS THE NEW, EXPLICIT LOGIN STEP ---
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }} # <-- Use the token from the 'auth' step
      # --- END OF NEW STEP ---

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # This tag is the same as before
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=inline
          cache-to: type=inline