name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  # --- THIS IS THE FIXED LINE ---
  IMAGE_NAME: ghcr.io/danielwill-1/my-diabetes-api
  # --- --- --- --- --- --- --- ---

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=inline
          cache-to: type=inline

      - name: Image pushed
        run: echo "Image ${{ env.IMAGE_NAME }}:latest pushed successfully."