# .github/workflows/ci-cd.yml

name: CI/CD - Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  # --- MAKE SURE THESE MATCH YOUR TERRAFORM VARIABLES ---
  PROJECT_ID: aiops-mini-project
  GCP_REGION: us-central1
  REGISTRY_NAME: my-app-registry
  SERVICE_NAME: diabetes-api-service # This will be the name of your image & service
  # --- --- --- --- --- --- --- --- --- --- --- ---

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for GCP authentication

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          # Use the secret you just created
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # This builds the full image tag, e.g.:
          # us-central1-docker.pkg.dev/aiops-mini-project/my-app-registry/diabetes-api-service:latest
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=inline
          cache-to: type=inline